export const screens = {
  COURSE_LIST: "COURSE_LIST",
  COURSE_DETAILS: "COURSE_DETAILS",
  SUBJECT_LIST: "SUBJECT_LIST",
  LESSON_DETAILS: "LESSON_DETAILS",
  ACCOUNT: "ACCOUNT",
  SETTINGS: "SETTINGS",
  PROFILE: "PROFILE",
  PROFILE_EDIT: "PROFILE_EDIT",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  FEEDBACK: "FEEDBACK",
  // LESSON_DETAILS: 'LESSON_DETAILS',
};
